# Generated by Django 4.2.29 on 2026-03-15 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('FRIEND_ACCEPTED', 'Friend Accepted'), ('TEAM_INVITE', 'Team Invitation'), ('TEAM_MEMBER_JOINED', 'Team Member Joined'), ('TEAM_MEMBER_LEFT', 'Team Member Left'), ('TOURNAMENT_STARTED', 'Tournament Started'), ('TOURNAMENT_FINISHED', 'Tournament Finished'), ('TOURNAMENT_INVITE', 'Tournament Invitation'), ('MATCH_SCHEDULED', 'Match Scheduled'), ('MATCH_RESULT_SUBMITTED', 'Match Result Submitted'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement')], help_text='Type of notification event', max_length=50)),
                ('message', models.TextField(help_text='Notification message to display to the user')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx')],
            },
        ),
    ]
