# Generated by Django 4.2.29 on 2026-03-15 18:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name (3-50 characters, unique case-insensitive)', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tag', models.CharField(help_text='Team tag/abbreviation (2-5 characters, e.g., PHX, NVX)', max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(5)])),
                ('slug', models.SlugField(help_text='URL-friendly identifier generated from team name', max_length=60, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='Cloudinary URL for team logo', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Team description or bio', max_length=1000)),
                ('banner_url', models.URLField(blank=True, help_text='Cloudinary URL for team banner image', max_length=500, null=True)),
                ('primary_color', models.CharField(blank=True, default='#ff4655', help_text='Primary brand color (hex format, e.g., #ff4655)', max_length=7)),
                ('secondary_color', models.CharField(blank=True, default='#111111', help_text='Secondary brand color (hex format, e.g., #111111)', max_length=7)),
                ('country', models.CharField(blank=True, help_text='Team country (e.g., Ecuador, Spain, USA)', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Team region (e.g., LATAM, NA, EU, APAC)', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified/official team badge')),
                ('sponsor', models.CharField(blank=True, help_text='Team sponsor (e.g., Red Bull, Monster Energy)', max_length=100)),
                ('founded_year', models.PositiveIntegerField(blank=True, help_text='Year the team was founded', null=True)),
                ('website', models.URLField(blank=True, help_text='Team website URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Team creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('captain', models.ForeignKey(help_text='Team captain with administrative permissions', on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_captain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamSettings',
            fields=[
                ('team', models.OneToOneField(help_text='Team these settings belong to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='teams.team')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Team visibility (public or private)', max_length=10)),
                ('join_policy', models.CharField(choices=[('open', 'Open'), ('request', 'Request to Join'), ('invite_only', 'Invite Only')], default='request', help_text='How users can join the team', max_length=15)),
                ('allow_requests', models.BooleanField(default=True, help_text='Allow users to request to join')),
                ('max_members', models.PositiveIntegerField(default=10, help_text='Maximum number of team members')),
            ],
            options={
                'verbose_name': 'Team Settings',
                'verbose_name_plural': 'Team Settings',
                'db_table': 'team_settings',
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('team', models.OneToOneField(help_text='Team these stats belong to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='teams.team')),
                ('matches_played', models.PositiveIntegerField(default=0, help_text='Total matches played')),
                ('matches_won', models.PositiveIntegerField(default=0, help_text='Total matches won')),
                ('matches_lost', models.PositiveIntegerField(default=0, help_text='Total matches lost')),
                ('tournaments_played', models.PositiveIntegerField(default=0, help_text='Total tournaments participated in')),
                ('tournaments_won', models.PositiveIntegerField(default=0, help_text='Total tournaments won')),
                ('winrate', models.DecimalField(decimal_places=2, default=0.0, help_text='Win rate percentage (0-100)', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When stats were last updated')),
            ],
            options={
                'verbose_name': 'Team Stats',
                'verbose_name_plural': 'Team Stats',
                'db_table': 'team_stats',
            },
        ),
        migrations.CreateModel(
            name='TeamSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('twitter', 'Twitter/X'), ('twitch', 'Twitch'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('website', 'Website')], help_text='Social media platform', max_length=20)),
                ('url', models.URLField(help_text='URL to the social media profile', max_length=500)),
                ('team', models.ForeignKey(help_text='Team these social links belong to', on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Social Link',
                'verbose_name_plural': 'Team Social Links',
                'db_table': 'team_socials',
                'indexes': [models.Index(fields=['team', 'platform'], name='team_social_team_id_348075_idx')],
                'unique_together': {('team', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', 'Captain'), ('player', 'Player'), ('manager', 'Manager'), ('coach', 'Coach')], help_text='Role of the user in the team', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('left', 'Left')], default='active', help_text='Status of the membership', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the membership was created')),
                ('team', models.ForeignKey(help_text='Team that the user is a member of', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
                ('user', models.ForeignKey(help_text='User who is a member of the team', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'db_table': 'team_memberships',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['team', 'status'], name='team_member_team_id_807061_idx'), models.Index(fields=['user', 'status'], name='team_member_user_id_aa7ff1_idx'), models.Index(fields=['team', 'role', 'status'], name='team_member_team_id_02e49e_idx')],
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message from the user', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the join request', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the request was last updated')),
                ('team', models.ForeignKey(help_text='Team the user wants to join', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='teams.team')),
                ('user', models.ForeignKey(help_text='User requesting to join', on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Join Request',
                'verbose_name_plural': 'Team Join Requests',
                'db_table': 'team_join_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'status'], name='team_join_r_team_id_1b89d1_idx'), models.Index(fields=['user', 'status'], name='team_join_r_user_id_349bd7_idx')],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', help_text='Status of the invitation', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the invitation was last updated')),
                ('invited_by', models.ForeignKey(help_text='Captain/manager who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='team_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(help_text='User being invited', on_delete=django.db.models.deletion.CASCADE, related_name='team_invites_received', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team sending the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Invite',
                'verbose_name_plural': 'Team Invites',
                'db_table': 'team_invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'status'], name='team_invite_team_id_4d755b_idx'), models.Index(fields=['invited_user', 'status'], name='team_invite_invited_ed0580_idx')],
                'unique_together': {('team', 'invited_user')},
            },
        ),
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('valorant', 'Valorant'), ('cs2', 'Counter-Strike 2'), ('lol', 'League of Legends'), ('dota2', 'Dota 2'), ('rocket_league', 'Rocket League'), ('overwatch2', 'Overwatch 2'), ('apex', 'Apex Legends'), ('fortnite', 'Fortnite'), ('fifa', 'FIFA'), ('cod', 'Call of Duty')], help_text='Game the team competes in', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the game was added')),
                ('team', models.ForeignKey(help_text='Team that plays this game', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Game',
                'verbose_name_plural': 'Team Games',
                'db_table': 'team_games',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['team', 'game'], name='team_games_team_id_ca0adb_idx')],
                'unique_together': {('team', 'game')},
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['tag'], name='teams_tag_b4ecd5_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['slug'], name='teams_slug_cf7c43_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['country'], name='teams_country_56e7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['region'], name='teams_region_652a69_idx'),
        ),
    ]
