# Generated by Django 4.2.29 on 2026-03-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(help_text='Game ID from RAWG API', unique=True)),
                ('name', models.CharField(help_text='Game name (e.g., Valorant, CS2)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier from RAWG', max_length=200, unique=True)),
                ('cover_url', models.URLField(blank=True, help_text='Game cover/background image from RAWG', max_length=500, null=True)),
                ('genres', models.JSONField(blank=True, default=list, help_text='Game genres (e.g., ["FPS", "Shooter"])')),
                ('platforms', models.JSONField(blank=True, default=list, help_text='Available platforms (e.g., ["PC", "PlayStation", "Xbox"])')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='RAWG rating (0-5)', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the game was cached locally')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time game data was updated')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rawg_id'], name='games_rawg_id_99b2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['slug'], name='games_slug_076f39_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='games_name_eb11e6_idx'),
        ),
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the game was added to team')),
                ('team', models.ForeignKey(help_text='Team that plays this game', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='teams.team')),
                ('game', models.ForeignKey(help_text='Game from RAWG cache', on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.game')),
            ],
            options={
                'verbose_name': 'Team Game',
                'verbose_name_plural': 'Team Games',
                'db_table': 'team_games',
                'ordering': ['created_at'],
                'unique_together': {('team', 'game')},
            },
        ),
        migrations.AddIndex(
            model_name='teamgame',
            index=models.Index(fields=['team', 'game'], name='team_games_team_id_c064d8_idx'),
        ),
    ]
