# Generated by Django 4.2.29 on 2026-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='battlenet_id',
            field=models.CharField(blank=True, help_text='Battle.net ID', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='User country', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord username (e.g., username#1234)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='psn_id',
            field=models.CharField(blank=True, help_text='PlayStation Network ID', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, help_text='User region/state', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='riot_id',
            field=models.CharField(blank=True, help_text='Riot ID (e.g., Username#TAG)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='steam_id',
            field=models.CharField(blank=True, help_text='Steam profile ID or URL', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='twitch_username',
            field=models.CharField(blank=True, help_text='Twitch username', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter/X handle (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_gamertag',
            field=models.CharField(blank=True, help_text='Xbox Gamertag', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_channel',
            field=models.CharField(blank=True, help_text='YouTube channel URL or handle', max_length=100),
        ),
    ]
