# Generated by Django 4.2.29 on 2026-03-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_battlenet_id_user_country_user_discord_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='steam_id',
        ),
        migrations.AddField(
            model_name='user',
            name='steam_url',
            field=models.URLField(blank=True, help_text='Steam profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='steam_username',
            field=models.CharField(blank=True, help_text='Steam username/display name', max_length=100),
        ),
    ]
