# Generated by Django 4.2.29 on 2026-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_steam_id_user_steam_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for avatar image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for profile banner image', max_length=500, null=True),
        ),
    ]
