# Generated by Django 4.2.29 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar_url_user_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invisible',
            field=models.BooleanField(default=False, help_text='User appears offline when invisible mode is enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last activity timestamp'),
        ),
    ]
