# Generated by Django 4.2.29 on 2026-03-15 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the friendship was created')),
                ('user1', models.ForeignKey(help_text='First user in the friendship', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(help_text='Second user in the friendship', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'db_table': 'friendships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user1', 'created_at'], name='friendships_user1_i_14f47d_idx'), models.Index(fields=['user2', 'created_at'], name='friendships_user2_i_1f3c25_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', help_text='Status of the friend request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the friend request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the friend request was last updated')),
                ('from_user', models.ForeignKey(help_text='User who sent the friend request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='User who received the friend request', on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friend Request',
                'verbose_name_plural': 'Friend Requests',
                'db_table': 'friend_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'status'], name='friend_requ_to_user_f1ac62_idx'), models.Index(fields=['from_user', 'status'], name='friend_requ_from_us_41dc33_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
