# Generated by Django 4.2.29 on 2026-03-13 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tournament name (3-100 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(help_text='URL-friendly identifier generated from tournament name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Tournament description', max_length=2000)),
                ('game', models.CharField(help_text='Game name (e.g., League of Legends, Valorant)', max_length=100)),
                ('banner', models.ImageField(blank=True, help_text='Tournament banner image (max 10MB, JPEG/PNG/WebP)', null=True, upload_to='tournament_banners/')),
                ('format', models.CharField(choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('round_robin', 'Round Robin'), ('swiss', 'Swiss')], default='single_elimination', help_text='Tournament bracket format', max_length=20)),
                ('participant_type', models.CharField(choices=[('teams', 'Teams'), ('players', 'Players')], default='teams', help_text='Type of participants (teams or individual players)', max_length=10)),
                ('max_participants', models.PositiveIntegerField(help_text='Maximum number of participants allowed')),
                ('registration_start', models.DateTimeField(help_text='When registration opens')),
                ('registration_end', models.DateTimeField(help_text='When registration closes')),
                ('start_date', models.DateTimeField(help_text='When tournament starts')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='draft', help_text='Current tournament status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tournament creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('organizer', models.ForeignKey(help_text='User who created and manages the tournament', on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_size', models.PositiveIntegerField(help_text='Size of the bracket (e.g., 8, 16, 32, 64)')),
                ('number_of_rounds', models.PositiveIntegerField(default=1, help_text='Number of rounds in the tournament')),
                ('third_place_match', models.BooleanField(default=False, help_text='Whether to include a third place match')),
                ('has_group_stage', models.BooleanField(default=False, help_text='Whether tournament has a group stage before playoffs')),
                ('match_format', models.CharField(choices=[('bo1', 'Best of 1'), ('bo3', 'Best of 3'), ('bo5', 'Best of 5')], default='bo1', help_text='Match format (Best of X)', max_length=10)),
                ('tournament', models.OneToOneField(help_text='Tournament these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Settings',
                'verbose_name_plural': 'Tournament Settings',
                'db_table': 'tournament_settings',
            },
        ),
        migrations.CreateModel(
            name='TournamentRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_text', models.TextField(help_text='Tournament rules and regulations in markdown format')),
                ('map_pool', models.CharField(blank=True, help_text='Allowed maps (comma-separated)', max_length=500)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit per match in minutes', null=True)),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Additional custom settings as JSON')),
                ('tournament', models.OneToOneField(help_text='Tournament these rules belong to', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Rules',
                'verbose_name_plural': 'Tournament Rules',
                'db_table': 'tournament_rules',
            },
        ),
    ]
